### PR TITLE
Trim whitespaces inside HTML nodes unless `maintain_inner_whitespaces` option is set

### LINKED ISSUE #34: Trim text inside HTML tags...
If you compare the following HTMLs are different when should be equals

```html
<ul>
  <li> Programación con objetos </li>
  <li> Ruby </li>
  <li> HTML </li>
</ul>
```

```html
<ul>
  <li>Programación con objetos</li>
  <li>Ruby</li>
  <li>HTML</li>
</ul>
```

### PR DESCRIPTION
**Pull request by Javi**
Fixes #34

### CODE REVIEW

**Comment by Javi** [comment]
I just pushed both success and failure test cases!

**Comment by flbulgarelli** [comment]
Hi! I have just refactored the code a little and added more tests. Also, i found some bugs and edge cases we were not covering - which is not actually a problem with this PR itself. 

I will push them as soon as I get internet and electricity back.

**Comment by Javi** [comment]
Would you like me to look at them?

**Comment by Javi** [comment]
+1 from me as well!

**Pull request merged**
